import type { Command } from "commander";
import { deleteRoster, expelRosterMember, issueRosterJoinKey, listRosterJoinKeys, revokeRosterJoinKey } from "../api.js";
import { relayUrl } from "../config.js";
import type { LineContext } from "../line-context.js";
import { deleteCached, forgetMembership, loadMemberships } from "../rosters.js";
import { ask } from "../tty.js";

type ResolveLine = (line: string | undefined) => LineContext | undefined;
type Membership = ReturnType<typeof loadMemberships>[number];
const find = (ctx: LineContext, name: string): Membership => loadMemberships(ctx.paths).find((r) => r.name.toLowerCase() === name.toLowerCase()) ?? (() => { throw new Error(`No roster named "${name}" — run \`agentcall roster list\`.`); })();
const secret = async (flag?: string) => { const value = flag ?? process.env.AGENTCALL_ADMIN_SECRET ?? (await ask("Admin secret: ")).trim(); if (!value) throw new Error("An admin secret is required."); return value; };
const confirm = async (name: string, consequence: string, yes?: boolean) => { if (!yes && (await ask(`${consequence} Type the roster name "${name}" to continue: `)).trim() !== name) throw new Error("Confirmation did not match; nothing was changed."); };

export function register(roster: Command, lineFor: ResolveLine): void {
  roster.command("expel").description("remove a member using the roster admin secret").argument("<name>").argument("<handle>").option("--admin-secret <secret>", "admin secret (prefer AGENTCALL_ADMIN_SECRET to avoid shell history)").option("--line <name>", "line to act as (defaults to the primary line)").action(async (name: string, handle: string, o: { adminSecret?: string; line?: string }) => { const c = lineFor(o.line); if (!c) return; try { const m = find(c, name); await expelRosterMember(m.relay, { org: c.config.org, handle: c.config.handle, token: c.config.token }, m.roster_id, handle, await secret(o.adminSecret)); console.log(`Expelled ${handle}. Revoke any join key they may still know.`); } catch (e) { console.error(e instanceof Error ? e.message : String(e)); process.exitCode = 1; } });
  const key = roster.command("key").description("issue, list, and revoke scoped roster join keys");
  key.command("issue").description("issue a one-off join key (use --reusable for a shared key)").argument("<name>").option("--admin-secret <secret>", "admin secret (prefer AGENTCALL_ADMIN_SECRET to avoid shell history)").option("--description <text>", "short label shown by `roster key list`", "").option("--expires-in <days>", "expiry in days (1-90)", (v) => Number.parseInt(v, 10), 30).option("--reusable", "allow more than one member to use this key").option("--line <name>", "line to act as (defaults to the primary line)").action(async (name: string, o: { adminSecret?: string; description: string; expiresIn: number; reusable?: boolean; line?: string }) => { const c = lineFor(o.line); if (!c) return; try { const m = find(c, name); if (!Number.isInteger(o.expiresIn) || o.expiresIn < 1 || o.expiresIn > 90) throw new Error("--expires-in must be an integer from 1 to 90."); const out = await issueRosterJoinKey(m.relay, { org: c.config.org, handle: c.config.handle, token: c.config.token }, m.roster_id, await secret(o.adminSecret), { description: o.description, expiresInDays: o.expiresIn, reusable: Boolean(o.reusable) }); console.log(`Join key (shown once): ${out.join_key}`); console.log(`Prefix: ${out.key.prefix}  Expires: ${new Date(out.key.expires_at).toISOString()}`); } catch (e) { console.error(e instanceof Error ? e.message : String(e)); process.exitCode = 1; } });
  key.command("list").description("list join-key metadata without revealing secrets").argument("<name>").option("--admin-secret <secret>", "admin secret (prefer AGENTCALL_ADMIN_SECRET to avoid shell history)").option("--line <name>", "line to act as (defaults to the primary line)").action(async (name: string, o: { adminSecret?: string; line?: string }) => { const c = lineFor(o.line); if (!c) return; try { const m = find(c, name); const keys = await listRosterJoinKeys(m.relay, { org: c.config.org, handle: c.config.handle, token: c.config.token }, m.roster_id, await secret(o.adminSecret)); if (!keys.length) return console.log("No join keys."); const now = Date.now(); for (const k of keys) console.log(`${k.prefix}\t${k.revoked_at !== null ? "revoked" : k.expires_at <= now ? "expired" : k.used && !k.reusable ? "used" : "active"}\t${k.reusable ? "reusable" : "one-off"}\t${new Date(k.expires_at).toISOString()}\t${k.created_by}\t${k.description}`); } catch (e) { console.error(e instanceof Error ? e.message : String(e)); process.exitCode = 1; } });
  key.command("revoke").description("revoke one join key; --evict removes only members admitted by it").argument("<name>").argument("<prefix>").option("--admin-secret <secret>", "admin secret (prefer AGENTCALL_ADMIN_SECRET to avoid shell history)").option("--evict", "remove members admitted by this key").option("--yes", "confirm targeted eviction").option("--line <name>", "line to act as (defaults to the primary line)").action(async (name: string, prefix: string, o: { adminSecret?: string; evict?: boolean; yes?: boolean; line?: string }) => { const c = lineFor(o.line); if (!c) return; try { const m = find(c, name); if (o.evict) await confirm(name, `This removes members admitted by key ${prefix}.`, o.yes); const out = await revokeRosterJoinKey(m.relay, { org: c.config.org, handle: c.config.handle, token: c.config.token }, m.roster_id, prefix, await secret(o.adminSecret), Boolean(o.evict)); if (o.evict) deleteCached(c.paths, name); console.log(`Revoked ${out.prefix}.${o.evict ? ` Evicted ${out.evicted} member(s).` : " Existing members were retained."}`); } catch (e) { console.error(e instanceof Error ? e.message : String(e)); process.exitCode = 1; } });
  roster.command("delete").description("permanently delete a roster while retaining its relay audit events").argument("<name>").option("--admin-secret <secret>", "admin secret (prefer AGENTCALL_ADMIN_SECRET to avoid shell history)").option("--yes", "confirm deletion").option("--line <name>", "line to act as (defaults to the primary line)").action(async (name: string, o: { adminSecret?: string; yes?: boolean; line?: string }) => { const c = lineFor(o.line); if (!c) return; try { const m = find(c, name); await confirm(name, "Roster deletion cannot be undone.", o.yes); await deleteRoster(m.relay, { org: c.config.org, handle: c.config.handle, token: c.config.token }, m.roster_id, await secret(o.adminSecret)); forgetMembership(c.paths, name); deleteCached(c.paths, name); console.log(`Deleted "${name}"; relay audit events were retained.`); } catch (e) { console.error(e instanceof Error ? e.message : String(e)); process.exitCode = 1; } });
  roster.command("forget").description("drop only the local roster record; use `roster leave` to remove relay membership").argument("<name>").option("--line <name>", "line to forget it for (defaults to the primary line)").action((name: string, o: { line?: string }) => { const c = lineFor(o.line); if (!c) return; try { forgetMembership(c.paths, name); console.log(`Forgot "${name}" locally. Your membership on the relay is unchanged; use \`roster leave\` for removal.`); } catch (e) { console.error(String(e instanceof Error ? e.message : e)); process.exitCode = 1; } });
}
